spring:
  redis:
    #Redis数据库索引（缓存将使用此索引编号的数据库）
    database: 12
    #Redis服务器地址
    host: 39.98.38.238
    #Redis服务器连接端口
    port: 8500
    #Redis服务器连接密码（默认为空）
    password:
    #连接超时时间 毫秒（默认2000）
    #请求redis服务的超时时间,这里注意设置成0时取默认时间2000
    timeout: 5000
