spring:
  cloud:
    gateway:
      routes:
        - id: business
          uri: lb://reliable-business-manager
          order: 0
          predicates:
            - Path=/business/**
            - Method=POST
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar
            - RemoveRequestHeader=Origin
            - Validate=true
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback/wechat/pay/order
        - id: notify
          uri: lb://reliable-wechat-pay-notify
          order: 0
          predicates:
            - Path=/paynotify/**
            - Method=POST
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar
            - RemoveRequestHeader=Origin
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback/wechat/pay/order