spring:
  datasource:
    url: jdbc:mysql://39.98.38.238:8400/reliable?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: reliable
    password: sqlpasswd@reliable
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
