spring:
  datasource:
    url: jdbc:mysql://39.98.38.238:8400/test
    username: lnnu
    password: lnnupasswd
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
